services:
  nginx:
    image: nginx:stable-alpine
    container_name: carbon_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
      - api

  app:
    image: sajibsd013/carbon-app
    container_name: carbon_app
    restart: always
    expose:
      - "3000"

  api:
    image: sajibsd013/carbon-api
    container_name: carbon_api
    restart: always
    expose:
      - "8000"